### ISSUE TITLE
The phpcs report contains invalid json

### ISSUE THREAD

**Issue by frazras** [ikappas/vscode-phpcs#100]
I'm getting this error in the vscode notification interface.
`"phpcs: The phpcs report contains invalid json. Please review "Diagnosing Common Errors" in the plugin README`"

It just appeared recently, I also recently upgraded vscode (10.20.1) but it was working even after that, not sure why it just popped up.

I went to the README file and saw this:

> ## Diagnosing common errors
>### The phpcs report contains invalid json
>This error occurs when something goes wrong in phpcs execution such as PHP Notices, PHP Fatal Exceptions, Other Script Output, etc, most of which can be detected as follows:
>Execute the phpcs command in your terminal with --report=json and see whether the output contains anything other than valid json.
>> **NOTE:** The '-q' parameter is automatically passed on phpcs v.2.6.2 and above to suppress such errors. Please update `phpcs` to a version >=2.6.2.

I have the latest phpcs
````
$ phpcs --version
PHP_CodeSniffer version 3.2.3 (stable) by Squiz (http://www.squiz.net) 
````
I tested the output of phpcs with a json linter and it returned no errors
`phpcs --report=json index.php >output.json`

I am not certain what else I can do from here. Can someone please help me with an idea on how to fix this?

**Comment by ikappas** [comment]
@frazras Is this a project based phpcs installation?

**Comment by frazras** [comment]
@ikappas No, this was a global setup

**Comment by ikappas** [comment]
@frazras Are you using the default PSR2 standard or some other?

**Comment by frazras** [comment]
@ikappas I am using the Drupal coding standard.
Here are my settings:
```
{
   "editor.tabSize": 2,
   "editor.renderWhitespace": "boundary",
   "files.trimTrailingWhitespace": true,
   "files.autoSave": "afterDelay",
   "git.confirmSync": false,
   "phpcs.standard": "/home/frazras/.config/composer/vendor/drupal/coder/coder_sniffer/Drupal",
   "window.zoomLevel": 1,
   "git.autofetch": true,
   "window.menuBarVisibility": "default",
   "gitlens.gitExplorer.files.layout": "tree"
}
```

**Comment by ikappas** [comment]
@frazras See issue #93 as it is probably relevant to your issue. Let me know if it helps

**Comment by ikappas** [comment]
@frazras More specifically try "phpcs.autoConfigSearch" : "false"

**Comment by frazras** [comment]
@ikappas no such luck on either count.
The thing I find weird is that it was working fine before then it just stopped working :-/

**Comment by ikappas** [comment]
@frazras This error, as described in the readme, means that the output of the phpcs command is not valid json. This can happen when additional messages, are appended to the phpcs json output such as PHP Exceptions, Errors, progress, etc. On recent versions of PHP_CodeSniffer these should be suppressed by the -q option which is applied automatically by vscode-phpcs. 

So for global setups I can only provide a basic checklist like:

1. Verify that php is installed and available globally. 

```bash
~ $ cd /path/to/your/project
path/to/your/project $ php --version
```

2. Verify that phpcs is installed using your prefered method.

```bash
~ $ cd /path/to/your/project
path/to/your/project $ phpcs --version
```

3. When using a custom coding standard verify that it is registered with phpcs according to your preferred installation method.

```bash
~ $ cd /path/to/your/project
path/to/your/project $ phpcs -i
```

4. Verify that phps  --report=json returns **only** valid json according to your preferred installation method.

```bash
~ $ cd /path/to/your/project
path/to/your/project $ phpcs --standard="<your-coding-standard-name>" -q --report=json --encoding=UTF-8 path/to/your/file.php
```

If your were to switch to a project setup, you could create a reproduction repo that I could have a look.

**Comment by rawzone** [comment]
> More specifically try "phpcs.autoConfigSearch" : "false"

I also had this problem, however for me this fixed the issue.

Edit: Okay spoke to soon - The problem is still there.

**Comment by ikappas** [comment]
@frazras @rawzone The only other thing I can suggest is cloning this repo and debug to see the error that is thrown in phpcs-server/src/linter.ts:235

**Comment by blueo** [comment]
I get this error when viewing a php file in the diff mode (ie the split screen you get when selecting a changed file in the version control tab)

**Comment by msaari** [comment]
I bumped into this same issue, but the JSON produced by the command line tool was clean.

I think the problem in my case might be caused by having a fairly large file (2500+ lines), with lots of errors. My computer had the php thread running at 99% CPU for a while, so perhaps php wasn't responding as fast as expected?

Disabling the PHPCS extension and then enabling it again seems to have fixed the issue for now.

**Comment by gregsullivan** [comment]
I encountered this issue and tracked it down to my global version of phpcs being incompatible with the Drupal standards:

https://www.drupal.org/node/2809335

(Coder requires phpcs version >=2.7.0, <3.0. I had the most recent version installed. Downgrading to 2.9.x solved the problem.)

**Comment by frazras** [comment]
Awesome!  Thanks @gregsullivan this worked for me! I was literally pulling my hair out of my bald head for this, I felt like I was writing bad code for the past 2 weeks :-D

See results of what I did below, I ran it both locally and globally.

```
$composer global require squizlabs/php_codesniffer:2.7.0
Changed current directory to /home/frazras/.config/composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating squizlabs/php_codesniffer (3.2.3 => 2.7.0): Downloading (100%)         
Writing lock file
Generating autoload files

```

@ikappas thanks also for writing this awesome plugin. By scanning through the code,
you've also inspired me to write my own plugin

**Comment by gregsullivan** [comment]
No problem, @frazras! I'm not sure about the differences between versions, but you could also use 2.9.x to keep it at the most recent <3.0 version. Looking at my `composer.lock`, Drupal Coder currently requires ">=2.8.1 <3.0", which (as of this morning) ends up installing 2.9.1.

Thanks for starting this thread—it got me pointed in the right direction.
