### ISSUE TITLE
Input file being set wrongly

### ISSUE THREAD

**Issue by premedios** [ikappas/vscode-phpcs#103]
Your extension is running the following:

`./vendor/bin/phpcs --report=json -q --encoding=UTF-8 --error-severity=5 --warning-severity=5 --stdin-path=/Users/Jaime/Developer/laravel/blog/app/user.php`

--stdin-path should not be set the full path of the file. I ran this in terminal (MAC) and phpcs said I'm not specifying a file or folder to lint.

Is there a configuration I need to set or do you need to fix your extension?

**Comment by ikappas** [comment]
@premedios The extension is not running the above mentioned command. Instead it runs the following  (translated for bash):
```bash
./vendor/bin/phpcs --report=json -q --encoding=UTF-8 --error-severity=5 --warning-severity=5 --stdin-path=/Users/Jaime/Developer/laravel/blog/app/user.php - < /Users/Jaime/Developer/laravel/blog/app/user.php
```
Also have a look at https://github.com/squizlabs/PHP_CodeSniffer/issues/1440

**Comment by ikappas** [comment]
@premedios Did you resolve your issue?

**Comment by premedios** [comment]
@ikappas It resolved itself. I have no idea how. Maybe an update to vscode or a restart.

**Comment by roborourke** [comment]
@ikappas I'm getting this error with 1.0.5, the error report suggests that the command is the one in the original comment and not the one you reference in this comment https://github.com/ikappas/vscode-phpcs/issues/103#issuecomment-370266404

It might be to do with php 7.3 which seems to always output a warning about using `continue` vs `break`, seems to do so even if I set `display_errors` to `Off` in my ini file...

**Comment by roborourke** [comment]
Yep, it's a combination of an older 2.x version of `phpcs` and PHP 7.3. The `phpcs` version is a requirement of a project I'm on. Hopefully can get our coding standards updated soon but takes time!
