### ISSUE TITLE
Shows this error in every php file. Tried to fix in many ways but unable to fix this.

### ISSUE THREAD

**Issue by iyashpal** [ikappas/vscode-phpcs#105]
[phpcs] End of line character is invalid; expected "\n" but found "\r\n"
[phpcs] Whitespace found at end of line

![code](https://user-images.githubusercontent.com/37584776/37778685-8d98287a-2e10-11e8-8a17-dc983dcf03bb.png)

**Comment by ikappas** [comment]
@Yash-Pal This looks like a .gitattributes issue. Please check your git configuration for line endings on checkout/checkin.

**Comment by iyashpal** [comment]
Can you please help me out to fix this. I am using windows 10 OS.

Thanks!

**Comment by ah2048** [comment]
@Yash-Pal Just type "Change End of Line Sequence" in command palette and select "LF"

**Comment by iyashpal** [comment]
@abdallahamin Thank you for your kind help.
