### ISSUE TITLE
Unable to locate phpcs

### ISSUE THREAD

**Issue by benriga** [ikappas/vscode-phpcs#11]
I am trying to use VS Code and phpcs on a local system running xampplite.  As a result, php and phpcs are not installed in c:\php but rather are in C:\xampplite\php.  Is there a setting in the phpcs extension that would allow me to point it to the right spot?

I have added C:\xampplite\php to my PATH but when I do that I get the message: Report type "json" not known

Any guidance to get this working?

Thanks,
Ben

**Comment by tariqabulaila0** [comment]
I am having the same problem with the json warning.

**Comment by arulpr** [comment]
I have the same error message

**Comment by ikappas** [comment]
@benriga @tariqabulaila0 @arulpr Can you please check whether 0.7.0 fixes your issues?

**Comment by ikappas** [comment]
I assume that this issue has been resolved in 0.7.0 so closing. Feel free to open a new issue if you do have problems

**Comment by 91Abdullah** [comment]
I'm still receiving this issue in version 0.7.0
