### ISSUE TITLE
Ability to select phpxs.xml path

### ISSUE THREAD

**Issue by muuvmuuv** [ikappas/vscode-phpcs#122]
I have all my confs in my Dropbox folder and want your extension to pull this phpcs.xml file instead of the one inside my project. Is this possible? if not this is a feature request :)

**Comment by jaredatch** [comment]
Look at the package details/settings here: https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs

Specifically, check out **phpcs.standard**.

```
The setting can be set to the absolute path to a custom coding standard:

{
    "phpcs.standard": "/path/to/coding/standard"
}
or you can use the path to a custom ruleset:

{
    "phpcs.standard": "/path/to/project/phpcs.xml"
}
The setting can be set to your workspace relative path to a custom coding standard:

{
    "phpcs.standard": "./vendor/path/to/coding/standard"
}
or you can use the path to your project's custom ruleset:
```

**Comment by muuvmuuv** [comment]
Oh sorry I missed that, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
