### ISSUE TITLE
PSR12 Support?

### ISSUE THREAD

**Issue by AdamMarton** [ikappas/vscode-phpcs#156]
Hi There,

Would you mind adding [PSR12 support](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.5.0)?

Currently I'm getting the following error when setting standard to `PSR12`:

```
phpcs: The "PSR12" coding standard is not installed. Please review your configuration an try again.
```

Cheers,

**Comment by josias-r** [comment]
Do you have the latest version of [phpcs](https://github.com/squizlabs/PHP_CodeSniffer/releases) installed (currently v3.5.0)?
It's working with my installation.

vscode-phpcs is only a wrapper for phpcs itself.

**Comment by AdamMarton** [comment]
Hi @josias-r ,

Interestingly enough, I have. Running it in command line works just fine. Do you have any idea what could be the issue?

**Comment by AdamMarton** [comment]
Just to be sure I've set PSR12 as default standard, still no luck.

**Comment by AdamMarton** [comment]
Setting PHPCS:Executable Path in settings resolves the issue.

**Comment by josias-r** [comment]
Setting the composerjson path should also work.
