### ISSUE TITLE
Is it simple to add js and css as languages checked with phpcs.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [ikappas/vscode-phpcs#17]
How would one do this?

**Comment by ikappas** [comment]
@LiamKarlMitchell This is not available at this time.

**Comment by bwaindwain** [comment]
To do this, modify `out/src/extension.js` and change

`documentSelector: ["php"],`

to 

`documentSelector: ["php", "css", "javascript"],`

also, modify package.json and change

```
"activationEvents": [
	"onLanguage:php"
],
```

to

```
"activationEvents": [
	"onLanguage:php", "onLanguage:css", "onLanguage:javascript"
],
```

also, see [#159](https://github.com/ikappas/vscode-phpcs/issues/159) about `--extensions` command line argument. You'll need to add `,css,js` to the list.

I should do a pull request someday... 

EDITED Sept-2020 to add some things I missed, maybe to keep up with VSCode's changes (?).
