### ISSUE TITLE
Add setting to set the phpcs path or search for it properly

### ISSUE THREAD

**Issue by artberri** [ikappas/vscode-phpcs#18]
When the plugin search for composer it should look also for the location of the `bin` dir instead of hardcoding `./vendor/bin` in https://github.com/ikappas/vscode-phpcs/blob/c0a7d6076161a8427b8fbc86377928f010f3bec4/phpcs-server/src/linter.ts#L134

Take into account that Composer allows to customize that folder, for example:

```
    "config": {
        "bin-dir": "bin"
    },
```

I'll try to get some time to make a pull request, but I'm not sure if I'm going to be able.

**Comment by josephzidell** [comment]
I need this also. My path is `vendors/bin`

**Comment by ikappas** [comment]
Closing this in favor of #23
