### ISSUE TITLE
High CPU on multiple file changes

### ISSUE THREAD

**Issue by anibalsanchez** [ikappas/vscode-phpcs#19]
The extension works great! So, I guess this is an improvement to work fine with big projects.

When you change multiple files in a project, for example 100 files, vscode-phpcs fires simultaneous 100 processes.... and CPU is overloaded.

There is also a second (weird) case when CPU is overloaded. When VSCode tries to write a file with no write permissions, it fires a change event to all files in a project! In my case, it can be easily 200-300 simultaneous processes running phpcs.

I'm currently disabling the extension with "phpcs.enable": false.

It would be better to have a feature to disable it per project .... or a CPU processes limit to 1 (the file that's being edited.... and not all changes files).

**Comment by ikappas** [comment]
@anibalsanchez Thank you for reporting this issue. Can you please elaborate a bit more on your use case. 

Btw, I have just released 0.7.0 which incorporates changes to the language server implementation. So please check whether any of your issues are resolved by this yersion.

**Comment by anibalsanchez** [comment]
I will re-check the case in the new version. 

The case is simple. You copy 100 files into your project folder and vscode-phpcs fires at least 10-20 php instances to check every file..... there is no other solution than kill vscode and all php instances.

**Comment by ikappas** [comment]
@anibalsanchez 
My team is involved in WordPress development so we always have projects that consist of several thousand php files but I have not observed this issue. 

Also, phpcs linting is triggered when a file is opened and then only when a file is saved. So unless you are opening 100 files at the same time I can't understand what is going on.  

Can you please elaborate on `copy 100 files into your project folder`, meaning the exact steps to trigger this issue.

Thank you in advance for looking into this.

**Comment by anibalsanchez** [comment]
I haven't been able to reproduce it recently.

Case solved!

**Comment by jrfoell** [comment]
I'd like to reopen this ticket. This happens to me all the time when I'm switching between two branches in git that have a significant amount of files added/changed. It seems like vscode spawns an instance of phpcs for every file changed or added. The result is an insane load while they run - to the point where it seems like my computer has locked.

![phpcs-takover](https://user-images.githubusercontent.com/630830/31199587-790f95aa-a91d-11e7-86dd-601f927b9cc8.png)

Not sure if there's a setting in vscode to limit the number of phpcs instances it will run?

**Comment by glaucomorais** [comment]
2019 and the problem getting even bigger!

Now when I type something in a PHP file, phpcs spawns PHP Cli and they live until I kill the process.
Sometimes phpcs decides to lint every file and the "phpcs is linting N files" goes on and on and never stops unless every spawned PHP Cli is killed.
