### ISSUE TITLE
phpcs: Unable to locate phpcs (php installed, pear installed, phpcs intalled)

### ISSUE THREAD

**Issue by Janne252** [ikappas/vscode-phpcs#2]
**Edit: Restarting the system fixed the issue.** Looks like I now have the same issue as described [here](https://github.com/ikappas/vscode-phpcs/issues/1).

Hey,

I'm getting the error "phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally." on VS Code.

PHP is installed in E:\php
PEAR is installed in E:\php
phpcs is installed in E:\php\pear\PHP\CodeSniffer (phpcs is also available in E:\php)

What am I supposed to add to the global path, assuming it's the Windows environment variable "Path"?
I've tried a lot of different paths and none seem to work.

**Comment by ikappas** [comment]
Thank you for your feedback.

The phpcs executable must be accessible in the global path and a restart maybe required in Windows.
I am closing this issue as you seem to be experiencing an other now.
