### ISSUE TITLE
Can't locate phpcs on macOS

### ISSUE THREAD

**Issue by Swift-R** [ikappas/vscode-phpcs#24]
So I installed VSCode, the phpcs extension and then phpcs using PEAR:

`sudo pear install phpcs` (does not work without sudo: No releases available for package "pear.php.net/phpcs")

After restarting VSCode I get the message:

> phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.

`which phpcs` returns `/usr/local/bin/phpcs`

Anyone?

**Comment by oknixus** [comment]
@Swift-R me too. I has searched solution with Google since yesterday. But nothing help to resolve this problem. And there is not enough detail in the author's docs

**Comment by Swift-R** [comment]
From what I've read, the issue is with VSCode itself. It doesn't allow extensions to use anything externally anymore.

**Comment by gabrielboliveira** [comment]
I was having this same issue. There are two ways I was able to fix:

1. Install dependency on project-level (refer to [this README](https://github.com/ikappas/vscode-phpcs/tree/master/phpcs#project-wide-installation))
2. Fix phpcs installation.

What I mean to fix phpcs installation is that for some reason installing with pear (via this [other method](/Users/gabrieloliveira/.composer/vendor/bin/phpcs)) was causing an issue to not load on VSCode, and also break on console. 

I installed it globally with composer, and also this installation should be the only one to be pointed on your PATH:

```sh
$ where phpcs
> /Users/gabrieloliveira/.composer/vendor/bin/phpcs
```

Before this, I had the pear installation and two of composer linked to phpcs, for some reason still didn't work. After I removed the pear and composer duplicated entry, VSCode worked successfully.

**Comment by gwagroves** [comment]
- Installed plugin
- Installed phpcs globally using composer
- Symlinked `/Users/[user]/.composer/vendor/bin/phpcs` to `/usr/local/bin/phpcs`
- Restarted vscode
- Worked!

**Comment by ikappas** [comment]
@Swift-R @oknixus @gwagroves @gabrielboliveira Can you please check whether 0.7.0 fixes your issues?

**Comment by Swift-R** [comment]
@ikappas looks like it's working now. I've switched back to Atom in the meanwhile for various reasons and it seems that it's working differently. For example, with the exact same code, Atom reports one line having more than 120 characters and a missing namespace while VSCode reports a missing doc comment for a class and a missing blank line before the tags in a doc comment in a method.

**Comment by ikappas** [comment]
@Swift-R Are you using global phpcs or project specific with composer?

**Comment by Swift-R** [comment]
Global

**Comment by ikappas** [comment]
@Swift-R I have switched to using stdIn instead of file parsing and setup utf8 encoding similarly to Atom in v.0.8.0. So I am closing this issue and feel free to test 0.8.0 until it is released!

**Comment by joneslloyd** [comment]
This is also an issue for me by the way. I'm running `Version 1.10.2 (1.10.2)`, and get the error `phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.`.

I tried something akin to @gwagroves' fix, so that it now looks like this:
![screen shot 2017-03-29 at 16 29 26](https://cloud.githubusercontent.com/assets/997427/24459883/ec404206-149c-11e7-9f80-00aa63c1344a.png)

But unfortunately I still get this error.

**Comment by grEvenX** [comment]
@ikappas I'm having the same problem. How can we help test 0.8.0 before it's oficially released with VSCode?

**Comment by Wrenbjor** [comment]
ok it needs to be globally installed via composer for the current versions of VSCode to see it.

Just run:

`    include_once "/usr/share/pear/PHP/CodeSniffer/autoload.php";
`
