### ISSUE TITLE
Add label to extension message

### ISSUE THREAD

**Issue by SidIcarus** [ikappas/vscode-phpcs#27]
Request:
When you have more then one lint-type extension populating the Problems panel, having them label helps know where that message is coming from. This is helpful when you are first starting out and are still trying to determine what sort of rules you want them to be running. It also becomes annoying when more then one linter is unlabeled and you are looking to change the rules it runs.

linter.js: PhpcsPathResolver 3rd line up - message: ${message.message} 
just need to concat a string in front, such as "CS: " || "PHPCS: " || "phpCS: "

**Comment by ikappas** [comment]
@SidIcarus Thank you for reporting this issue. This is fixed in 0.7.0
