### ISSUE TITLE
Add phpcs.error_severity and phpcs.warning_severity

### ISSUE THREAD

**Issue by alex-pex** [ikappas/vscode-phpcs#29]
I'd like to be able to override the warning_severity (my CI tools doesn't care about warnings)
Eg: vendor/bin/phpcs . --standard=phpcs.ruleset.xml --warning-severity=0

There's no setting for this. Can you add those settings ?
/phpcs-server/src/linter.ts:43
/phpcs-server/src/linter.ts:281
/phpcs/package.json:33
/phpcs/README.md:56

(I would have posted a pull-request, but I don't know how to build and test a vscode extension)

**Comment by ikappas** [comment]
@alex-pex  This issue is implemented in the latest development branch and will be available through vscode-phpcs 0.8.0

**Comment by alex-pex** [comment]
Thank you!

**Comment by phaberest** [comment]
Is the development still active here? I see this feature has been implemented but is not tagged

**Comment by dorian-marchal** [comment]
Bump
