### ISSUE TITLE
为什么不把phpcs.phar文件放在你自己的扩展目录中一起发布

### ISSUE THREAD

**Issue by guodf** [ikappas/vscode-phpcs#3]
如果这样做，我们只需要安装php就可以了。
另一个原因：phpcs.phar如果有更新，那么你的vscode扩展插件phpcs也需要跟着更新，既然这样，那么把phpcs.phar和你的vscode扩展插件phpcs一起发布不是更好吗？！

**Comment by jimmyko** [comment]
Don't expect everyone can read Chinese in Github.
作者不是華人，用中文留言有用嗎?

**Comment by ikappas** [comment]
Well if someone can translate the issue, maybe I can be of assistance :)

**Comment by jimmyko** [comment]
Hi @ikappas,
He is asking if you can embed the phpcs.phar in vscode phpcs extension. If there is phpcs update, your extension have to update too, and vice versa.

**Comment by ikappas** [comment]
Thank you for your suggestion. 
Embedding phpcs.phar into the plugin is not something that I would like persue since it would involve embedding a php version as well for all platforms.
