### ISSUE TITLE
Lint multiple folders on a directory

### ISSUE THREAD

**Issue by elvishp2006** [ikappas/vscode-phpcs#30]
It would be nice if it had a setting so I can set the folders of my code.

phpcs example:
```shell
phpcs --standard=WordPress wp-content/themes/deugame/src wp-content/plugins/deugame-manager/src
```

**Comment by ikappas** [comment]
@elvishp2006 You can achieve this with a custom rulset.xml controlling include/exclude paths and standard. Let me know if this helps!

**Comment by elvishp2006** [comment]
Thanks for answering,
I'll try to do as you told me, but having this feature directly in extension makes it more powerful.

**Comment by ikappas** [comment]
@elvishp2006 No problem!
