### ISSUE TITLE
Non-red highlight color or option to customize

### ISSUE THREAD

**Issue by paulrrogers** [ikappas/vscode-phpcs#36]
It would be helpful if the highlight color were not red since that color is associated with errors. Ideally it could be customized.

**Comment by ikappas** [comment]
@paulrrogers Thank you for your proposal. 

Both VSCode and phpcs executable use red for errors and yellow for warnings. 

I don't see value in changing this or providing additional support for something that will rarely be used (if at all).

**Comment by origamifreak2** [comment]
I agree that this would be helpful. If it doesn't make sense to put in a setting, then is there a way to change this with a custom ruleset maybe? Any guidance or directions would be appreciated

**Comment by origamifreak2** [comment]
For those who want to show all warnings differently, I found a hack that will allow you to do it. It's definitely a hack though, so next time the you update the plugin or re-install it, it will overwrite the changes you've made.

Steps

1. open file `~/.vscode/extensions/ikappas.phpcs-1.0.5/server/src/linter.js`
2. find code that says `vscode_languageserver_1.DiagnosticSeverity` (this should be followed by `.Hint`, `.Information`, `.Warning`, or `.Error`)
3. change the `.Hint`, `.Information`, `.Warning`, or `.Error` ending to whichever one you want
4. Restart vscode and the errors from phpcs will be displayed differently

    - `.Error` = red squiggly
    - `.Warning` = yellow squiggly
    - `.Information` = green squiggly
    - `.Hint` = three dots

@paulrrogers @ikappas

**Comment by cagross** [comment]
@origamifreak2 @ikappas this still the best way to change the highlight color of phpcs errors and warnings in VSCode?

I agree that phpcs errors should be styled differently from the built in VSCode errors/warnings (e.g. different color and/or font).  The errors reported by phpcs are non-critical, while the errors reported by VSCode can sometimes be critical errors (i.e. something that will result in a PHP fatal error).  It would be nice to see a distinction between the two.

**Comment by DanAlexson90** [comment]
I agree with @cagross, makes no sense that [phpcs](https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs) red squiggles everything.

**Comment by JPustkuchen** [comment]
@ikappas this is really a bad choice and brings the library close to unusable state in daily use. You can't distinguish code errors from code style WARNINGS anymore.

You're right, that ERRORS should be red, but code style, missing comment or whatever is no ERROR. An error is something that leads to broken functionality. Look at all kind of IDE's, I've never seen code style errors being displayed like syntax errors ever before, for good reasons.

This project is really impressive, and you've done a GREAT job, but the decision above should clearly be revised.
