### ISSUE TITLE
phpcs: The "WordPress-Extra" coding standard set in your configuration is not installed...

### ISSUE THREAD

**Issue by mwidmann** [ikappas/vscode-phpcs#38]
Been getting this error notification lately. phpcs is installed through brew and available at /usr/local/bin/phpcs

There is no other version of phpcs installed on my machine as far as I know and therefore the one in /usr/local/bin should be used.

The WordPress coding standards are installed

`→ phpcs -i`
`The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and WordPress-VIP`

**Comment by sethstha** [comment]
Once I had the same problem. Reinstalling `phpcs` and `WordPress coding standard` solved my problem

**Comment by mwidmann** [comment]
Thank you for the reply. In the meantime I figured out that somehow a second version of phpcs got installed on the machine through composer and that this version was used instead of the one in my path. I didn't want to investigate further so I added the WordPress-stuff to the installed_paths on this installation as well. Now it works.
