### ISSUE TITLE
Windows 10 warning for all php files: File appears to be minified and cannot be processed

### ISSUE THREAD

**Issue by bravo-kernel** [ikappas/vscode-phpcs#39]
I am having an issue where all php files opened in my Windows 10 Visual Studio Code IDE produce the following warning:

![afbeelding](https://cloud.githubusercontent.com/assets/230500/23825242/652d1fb0-0686-11e7-9722-c61470e2fb5c.png)

Full error message:

    file: 'file:///c%3A/Users/bravo/VScodeProjects/test-app/src/Controller/AppController.php'
    severity: 'Warning'
    message: 'File appears to be minified and cannot be processed'
    at: '1,1'
    source: 'phpcs'

Even this basic file is enough to trigger the warning:

```php
<?php
   print "the line above causes the trigger"
```

I am running:

- Windows 10
- Visual Studio Code 1.10.2
- PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( ZTS MSVC14 (Visual C++ 2015) x64 )
- PHP_CodeSniffer version 2.8.1 (stable) by Squiz (http://www.squiz.net)

I am creating this ticket because the warning only seems to occur in the IDE, the warning does not show when running `phpcs` against the exact same php files on both:

- my Windows machine (same phpcs as used by VSC and your extension)
- my Linux machine

All pointers highly appreciated.

**Comment by ikappas** [comment]
@bravo-kernel  Thank you for reporting this issue. Did you manage to resolve it?

**Comment by bravo-kernel** [comment]
I will recheck

**Comment by ikappas** [comment]
@bravo-kernel can you use the plugin from the development branch to make sure it works?

**Comment by bravo-kernel** [comment]
Googling like crazy 😉

**Comment by bravo-kernel** [comment]
I have invested two hours trying to get the phpcs-server to compile the extension but unfortunately to no avail. Any chance you could make the compiled dev version available (for download or something)?

**Comment by bravo-kernel** [comment]
![image](https://user-images.githubusercontent.com/230500/32144148-ad1e0e08-bcb4-11e7-9605-04cce73f18cb.png)

**Comment by ikappas** [comment]
@bravo-kernel Did you run the npm install task first?

**Comment by bravo-kernel** [comment]
Yes, I did (while trying to update your readme a little):

1. git clone my fork
2. install the VS Code npm extension
3. Open `phpcs` folder using VS Code
4. Run `npm install` command
5. Press F5

Tried it twice, once from a clean clone

**Comment by ikappas** [comment]
@bravo-kernel Try the following:

1. Open the phpcs project in vscode containing both client and server folders (root of this project)
2. Select run task from vscode menu and run npm install
3. Select run task from vscode menu and run compile
4. Go to debug sidebar and select Client+Server option am click debug

This should have you up and running ;)

**Comment by ikappas** [comment]
The documentation may need some updating :)

**Comment by bravo-kernel** [comment]
Thanks, attempting that right now. I will update the docs one I get this working 👍

**Comment by bravo-kernel** [comment]
Awesome instruction mr. @ikappas, much obliged.

I can confirm the error is resolved.  Would you mind sharing what the cause was?

ps: I will PR an update to the readme

**Comment by ikappas** [comment]
@bravo-kernel I am not really sure why this occured but a quick google search produced :
- [https://github.com/squizlabs/PHP_CodeSniffer/issues/720](https://github.com/squizlabs/PHP_CodeSniffer/issues/720)
- [https://github.com/squizlabs/PHP_CodeSniffer/issues/1626](https://github.com/squizlabs/PHP_CodeSniffer/issues/1626)

**Comment by bravo-kernel** [comment]
Sweet, thanks for the support !

**Comment by ikappas** [comment]
No problem! :)
