### ISSUE TITLE
how to use phpcs.ignore?

### ISSUE THREAD

**Issue by kassyn** [ikappas/vscode-phpcs#44]

**Comment by vargaLaszlo** [comment]
+1

**Comment by ikappas** [comment]
@kassyn 

Preparing for version 1.0.0 : 

### **phpcs.ignorePatterns**

[ Optional | **Type:** `array` | **Default:** `null` ]
This setting controls the files and directories to ignore when linting your documents. You may specify an array of glob patterns to ignore files and directories.

```json
{
    "phpcs.ignorePatterns": [
        "*/ignored-file.php",
        "*/ignored-dir/*"
    ]
}

**Comment by gusbemacbe** [comment]
@ikappas 

Chaírete, is there how to ignore problems and warnings? I have more than 100 problems and warnings, I find them annoying, everything is highlighted in red in all files. I am not speaking about of files and folders, but I want to ignore permanently only some problems.

**Comment by bartech101** [comment]
Is is possible to ignore all folders and then un-ignore specific folder inside like
`"wp-content/plugins/*",`
`"!wp-content/plugins/my-plugin/*"`

**Comment by ikappas** [comment]
@bartech101 No this is not possible because the `phpcs.ignorePatterns` configuration setting is being handled by PHP_Code_Sniffer [--ignore flag](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders)

**Comment by Benoit1980** [comment]
it would have been nice to have a right click "ignore" error as I am also 100s of issues and find this to be annoying. I will remove it for now until there is a solution for this. Thanks.

**Comment by buttflattery** [comment]
@ikappas although added the settings

```
 "phpcs.ignorePatterns": ["*/vendor/*", "*/web/*"],
```

 but after a while it still starts sniffing the vendor directory when working with `php` classes and namespaces and starts clogging the output console in vscode see image below
![image](https://user-images.githubusercontent.com/1536454/62172497-db057d80-b34b-11e9-93d2-b10f451d6db7.png)
