### ISSUE TITLE
Add support for automatic fixes

### ISSUE THREAD

**Issue by hajekj** [ikappas/vscode-phpcs#46]
Hi, is it possible to have the extension support a command to run the autofix on a file like described in here? https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically I think it would be a really helpful feature.

**Comment by ikappas** [comment]
@hajekj Thank you for submitting your suggestion.

This is a duplicate of #28 so I am closing this issue. Feel free to continue the conversation there!
