### ISSUE TITLE
Not showing N further errors or warnings

### ISSUE THREAD

**Issue by slifin** [ikappas/vscode-phpcs#47]
I have files in the project I'm working on that contain a lot of coding standard violations

<img width="636" alt="screen shot 2017-05-31 at 11 15 16" src="https://cloud.githubusercontent.com/assets/198857/26627455/76c886aa-45f2-11e7-8b6d-345ba45bc4b5.png">

Is it possible to see all the warnings and errors no matter how many there are?

**Comment by jackwilsdon** [comment]
This is a hard limit of VSCode, see Microsoft/vscode#9826.

**Comment by ikappas** [comment]
@slifin Thank you for submitting this issue.

As @jackwilsdon accurately explained this is a a hard limit of VSCode.
