### ISSUE TITLE
Add config to allow specifying phpcs executable location.

### ISSUE THREAD

**Issue by ADmad** [ikappas/vscode-phpcs#49]
The plugin currently checks whether package with name `squizlabs/php_codesniffer` is present under `packages` or `packages-dev` of `composer.lock` and if found uses the phpcs binary from `vendor/bin`. Now my project has a dev dependency which itself has php codesniffer as dependency causing `squizlabs/php_codesniffer` package to be present under `packages-dev` of `composer.lock` and hence the plugin uses the `vendor/bin/phpcs` binary. But I don't want that and instead want my globally installed phpcs to be used (available through environment path) which is configured as per my needs.

So it would be nice if there was an option to explicitly specify the phpcs executable location. That would also help resolve the issues like #48 where the plugin is unable to detect phpcs location.

**Comment by ADmad** [comment]
Turns out the checking of phpcs executable in environment paths is buggy which is what causes my particular issue. I have opened a PR to fix that.

Though it would still be nice to a config to simply specify phpcs and avoid avoid the path detection overhead.

**Comment by marabesi** [comment]
@ADmad good catch, I had to add the phpcs dependency just to get the plugin woking. As you said would be great to have the ability to set phpcs exacutable.

**Comment by pbarnum** [comment]
Turns out if you have phpcs as a dependency, but don't have it installed on your host machine (I use it within my docker container), and instead want to use the global installation reachable through the PATH, it will still only try running the project-specific composer version.

**Comment by ikappas** [comment]
@ADmad @pbarnum I will be implementing this option soon

**Comment by ADmad** [comment]
I tried the `develop` branch and the new `phpcs.executablePath` path seems to work as expected, allowing me to specify the phpcs executable location, which solves my problem.

**Comment by ikappas** [comment]
@ADmad Thank you for reporting your findings!

I' am closing this as resolved
