### ISSUE TITLE
Add ability to select phpcs

### ISSUE THREAD

**Issue by Paladin** [ikappas/vscode-phpcs#53]
I've a phpcs version installed globally. How about a config param, say "phpcs.path" that would allow me to insert the path for my global phpcs for the times I want to test a different version of phpcs with existing projects?

**Comment by oojacoboo** [comment]
ABSOLUTELY!  I'm using a composer installed version myself, but this plugin makes a gross assumption that my composer.json and src files are all sitting at the root of the project.  As a result, it's unable to find phpcs.  It also won't work with a globally installed version via homebrew, b/c of the composer dependencies necessary for other rules.

I got it worked with a nasty hack to my $PATH adding `./relative/path/to/vendor/bin`, after assuming that this plugin was looking at the project root.

Please add this configuration option.  Default to null and enable the automagic.  Thanks!

**Comment by ikappas** [comment]
@Paladin @oojacoboo Thank you for submitting this issue. I am closing this in favor of #49
