### ISSUE TITLE
Can support Windows 10 Wsl?

### ISSUE THREAD

**Issue by purocean** [ikappas/vscode-phpcs#54]

**Comment by purocean** [comment]
![image](https://user-images.githubusercontent.com/7115690/28497443-c34ba994-6fb9-11e7-94c0-6d1938da9643.png)

**Comment by purocean** [comment]
Solved!

```bat
@echo off
set v_params=%*

if defined v_params (
    set v_params=%v_params:\=/% 
)

bash -c "phpcs `echo %v_params:"=\"% | sed 's/Y:/\/mnt\/y/i'`"
```

**Comment by ikappas** [comment]
@purocean Good to know! Thank you for reporting this

**Comment by sagarrabadiya** [comment]
i am not getting any lint errors using above bat file i adjusted it to have C instead of Y drive, can you help me setting it up

**Comment by rollecode** [comment]
Thank you @purocean! I'm using your code but not getting any errors. It just says "phpcs is linting 1 document" and then nothing. Any way to see what it does / why no errors?
