### ISSUE TITLE
Support -s flag output

### ISSUE THREAD

**Issue by oojacoboo** [ikappas/vscode-phpcs#55]
The current error output doesn't tell you what rule definition originated the error.  This makes debugging and optimizing your rulesets significantly more difficult.

It's be nice if this information was included on the tooltip, but if not there, at least in the debug panel output.  My `phpcs.xml` file includes the -s flag argument, but it doesn't seem that's being respected with output.

**Comment by ikappas** [comment]
@oojacoboo I've just added support for this to the development branch. Can you test this and let me know whether it covers your use case?

**Comment by oojacoboo** [comment]
@ikappas struggling with testing these at the moment.  See #35.  It'd be nice if there were an easier way to test dev builds of extensions in vscode :/

**Comment by ikappas** [comment]
This has been implemented in 1.0.0-beta.x. You can enable this option by setting the following configuration:
```json
"phpcs.showSources" : true
```
