### ISSUE TITLE
What's the point ?

### ISSUE THREAD

**Issue by Juanses** [ikappas/vscode-phpcs#57]
I've struggled for hours to install phpcs and it just says "you have an error". It would be much more convinient if it tried to fix it. But it doesn't. I can't manage to indent correctly my code that I modify with ftp-simple as I guess does 90% of php coders in the world. So this extension is pointless.

**Comment by dingo-d** [comment]
If you have phpcs installed, you can use `phpcbf` command that will fix minor issues for you...
