### ISSUE TITLE
phpcs: The "WordPress" coding standard set in your configuration is not installed.

### ISSUE THREAD

**Issue by kirtangajjar** [ikappas/vscode-phpcs#58]
It has been set, I can set the standards through command line and it just works fine. However, I can't get it to work in vscode

**Comment by etiennejcharles** [comment]
To check your code standard installed via phpcs, in the commands line you should be able to run 
```
phpcs -i 
```

It should contain "WordPress" in the results, if not, it's not installed. see here 

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/2872476/30082523-191dc980-9259-11e7-8c90-1873b89454f2.png">

**Comment by shrop** [comment]
I am experiencing the same issue with my settings: `"phpcs.standard": "Drupal,DrupalPractice"`

"The "Drupal" coding standard set in your configuration is not installed." Related, does it only work with one standard at a time? 

Here are my phpcs -i results
`phpcs -i
The installed coding standards are Drupal, DrupalPractice, MySource, PEAR, PHPCS, PSR1, PSR2, Squiz and Zend`

**Comment by shrop** [comment]
It seems like it is working for me if I enter full paths for where they live on my file system. Would like to get it working again with the short names (and multiples if possible) :)

**Comment by kevinwhoffman** [comment]
Here is how I was able to get phpcs working with the WordPress coding standards.

1. Insert the following into `composer.json`:

```json
"require-dev": {
    "squizlabs/php_codesniffer": "^3.0",
    "wp-coding-standards/wpcs": "^0.13.1"
},
"scripts": {
    "post-install-cmd": [
        "\"vendor/bin/phpcs\" --config-set installed_paths vendor/wp-coding-standards/wpcs"
    ],
    "post-update-cmd": [
        "\"vendor/bin/phpcs\" --config-set installed_paths vendor/wp-coding-standards/wpcs"
    ]
}
```

2. Insert the following into your Visual Studio Code User Settings:

```json
"phpcs.enable": true,
"phpcs.standard": "WordPress"
```

3. Run `composer install` or `composer update`.

Now the WordPress coding standards in your `vendor` directory will be made available to phpcs within Visual Studio Code and you should begin to see PHP errors reported in you Problems panel as you type.

**Comment by dingo-d** [comment]
I have tried with projects that have vendor folder, and without, and it's not working...

**Comment by kevinwhoffman** [comment]
@dingo-d Please provide more information about what is not working.

Did you run `composer install` and confirm that you have a directory at `vendor/bin/phpcs`?

**Comment by dingo-d** [comment]
Yes, I have the vendor folder with `phpcs` installed with the specific coding standard. I have put in my settings

~~~json
"phpcs.enable": true,
"phpcs.standard": "vendor/infinum/coding-standards-wp/Infinum",
~~~

still get the 

> phpcs: Unexpected token in JSON at position 24379

error when opening any php file.

**Comment by ikappas** [comment]
@dingo-d  There is an issue with Infinum declaring default report type ([see here](https://github.com/infinum/coding-standards-wp/blob/master/Infinum/ruleset.xml#L16)) in the ruleset. You can verify this yourself by running the following command in your workspace root:
```bash
./vendor/bin/phpcs --report=json --standard=Infinum .
```
which will output the json report followed by the list of errors. That is why you get an error with all of your php files because the extension expects to get an json response from phpcs but instead gets something else.

For the record, and if Infinum was working properly you could have followed the following steps to set it up:

In order to configure Infinum with phpcs and composer you need to add the following snippet in your composer.json:
```json
"require-dev": {
    "squizlabs/php_codesniffer": "*",
    "infinum/coding-standards-wp": "^0.2.3"
},
"scripts": {
    "post-install-cmd": [
        "\"vendor/bin/phpcs\" --config-set installed_paths vendor/infinum/coding-standards-wp"
    ],
    "post-update-cmd": [
        "\"vendor/bin/phpcs\" --config-set installed_paths vendor/infinum/coding-standards-wp"
    ]
}
```

You can verify whether `Infinium` is available to your project's vendored phpcs by  running:
```bash
bash$ ./vendor/bin/phpcs -i
The installed coding standards are PEAR, PHPCS, Zend, PSR2, MySource, Squiz, PSR1 and Infinum
``` 

After that in your vscode settings.json:
```json
"phpcs.enable": true,
"phpcs.standard": "Infinum",
```

**Comment by ikappas** [comment]
@kirtangajjar Thank you for submitting this issue. Can you please provide some more information on how you have your project/phpcs/vscode setup?

**Comment by dingo-d** [comment]
Hi @ikappas thanks for the answer. I will update the standards with the correct post install and update scripts, although we had the post install commands set up in the composer file: [link](https://github.com/infinum/coding-standards-wp/blob/10b5a193f9d6945a92de2e701b87b67549451659/composer.json#L22).

As for `json` report, this seems like an upstream issue. I will report this in the PHPCS repo. If you specify the standard that has the standard defined, it should override it.

**Comment by kirtangajjar** [comment]
@ikappas I encountered this issue long time ago. Maybe I was able to solve it, or just gave up. I just can't recall. I would've loved to help, but unfortunately I can't as I don't recall much details. 

Even the project I was working on was kind of an assignment and I've finished it. Hence, I don't need this particular functionality now :(

**Comment by dingo-d** [comment]
I reported it to the official repo and will see what they'll say. In the meantime, the best course of actions would be to remove the report type from the standard altogether.

**Comment by ikappas** [comment]
@kirtangajjar No problem!  I will mark this issue as resolved. Please feel free to open a new issue if you continue to experience any issues.

**Comment by kirtangajjar** [comment]
@ikappas I have installed `phpcs` globally using composer. My `phpcs -i` output is:

```
The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, WordPress-VIP, WordPress, WordPress-Extra, WordPress-Docs and WordPress-Core
```
Yet I get the error mentioned in title when I set `phpcs.standard` to `WordPress`

**Comment by KamWis** [comment]
Same issue - bumping it up

**Comment by madbbb** [comment]
I ran into the same problem today. I have phpcs installed globally and phpcs into my project. My `phpcs -i` output includes all needed standards, but when I ran `vendor/bin/phpcs -i` it had it's own installed presets. So I had to configure phpcs installed in vendor/bin/ again `vendor/bin/phpcs --config-set installed_paths vendor/path-to-standards`

**Comment by KamWis** [comment]
I have also found the solution :) phpcs installation in project I am working with resides in `/vendor/squizlabs/php_codesniffer/scripts/phpcs` - therefore I needed to point it directly in the project's folder `/vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths ~/wpcs`

I mean - it's good that local installation overrides global settings. But an error is thrown at me when it happens and specific settings aren't present, is very unclear. I would be happy if instead of error `phpcs` could:
- in the case specified standard isn't met locally - search on the global scope (bubbling),
- the warning is shown that local settings aren't present for local installation (path to the installation) and global settings are used instead.

The second point is easier, though, and can still be implemented w/o first one. Even when global settings won't be used - error at least can point out to the path of the failing installation.

I believe either of those points would resolve bunch of issues :)

**Comment by GaryJones** [comment]
If you want to avoid having to manually registering the WPCS standards, try adding https://github.com/Dealerdirect/phpcodesniffer-composer-installer to your `require-dev` - it will automatically register the found standards and works great with WPCS.

**Comment by ngwebspinner** [comment]
I have phpcs installed globally so I can access it from any folder. I get the errors when I install wpcs in a folder other than the project root directory - phpcs -i says everything is okay, but vscode complains. 

What has worked for me is installing wpcs in the project root directory. With composer installed run: _composer create-project wp-coding-standards/wpcs:dev-master --no-dev_ from your project root directory (many thanks to Tom McFarlin for this -- https://code.tutsplus.com/tutorials/using-php-codesniffer-with-wordpress-installing-and-using-the-wordpress-rules--cms-26443). Inform phpcs of the location of your wpcs by running: _phpcs --config-set installed_paths wpcs_. Run: _phpcs -i_ to confirm that phpcs sees your WordPress standards. Set _phpcs.standard to WordPress_ in vscode. That's it.

**Comment by wpamitkumar** [comment]
i have found one solution :

-run this command from terminal
`phpcs --config-set default_standard WordPress`

and restart vscode.

**Comment by ihsanberahim** [comment]
I managed to solve it this way on my Mac

`composer global require wp-coding-standards/wpcs`
`phpcs --config-set installed_paths <my user dir>/.composer/vendor/wp-coding-standards/wpcs`

in settings:
```
    "phpcs.executablePath": "<my user dir>/.composer/vendor/bin/phpcs",
    "phpcs.standard": "WordPress",
```
