### ISSUE TITLE
phpcs: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by janverton** [ikappas/vscode-phpcs#60]
Hi there,

After doing a project wide installation of phpcs via composer and installing the plugin I get the following error every time the linter runs:

  phpcs: Cannot read property 'length' of null

Dev tools output is this:
```
{"method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/Path\/to\/File.php","diagnostics":[]},"jsonrpc":"2.0"}
```
Diagnostics seem to be empty, is it a configuration issue perhaps? When I run the command manually from the terminal it runs as expected

btw, phpcs version is this:
```
./vendor/bin/phpcs --version
PHP_CodeSniffer version 2.9.1 (stable) by Squiz (http://www.squiz.net)
```

Any help would be greatly appreciated! :)

**Comment by mrhn** [comment]
Having the same problem on the windows platform, thinking it can be the file path maybe? have not looked deeper into this.

**Comment by janverton** [comment]
It seems I had the wrong plugin with the same name installed, `phpcs 0.8.1` instead of `phpcs 0.7.0`. The latter one _does_ work! 👍

**Comment by AbhishekGhosh** [comment]
@janverton is correct. Use`phpcs 0.7.0` not `phpcs 0.8.1`. Do not install both together.
