### ISSUE TITLE
phpcs: Line exceeds 120 characters (Line contains 118 characters)

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [ikappas/vscode-phpcs#61]
I opened a file and this warning appeared.

![screen shot 2017-09-20 at 11 27 26 am](https://user-images.githubusercontent.com/5341310/30655905-eba8b5e6-9df7-11e7-8f0d-96c25b10bbd6.png)

**Comment by ikappas** [comment]
@MikeVelazcoMtz Thank your for submitting an issue!

I am not sure whether phpcs.phar counts line-endings. 
When you lint the same file in your terminal does this warning come up?

**Comment by eduardoklosowski** [comment]
I have the same problem. However it is something of phpcs, when calling `phpcs --encoding=UTF-8` works.

https://github.com/squizlabs/PHP_CodeSniffer/issues/1300

**Comment by ikappas** [comment]
@MikeVelazcoMtz @eduardoklosowski Can you please check whether vscode-phpcs 1.0.x solves your issues?

**Comment by eduardoklosowski** [comment]
I tested it with version 1.0.2 and it worked as expected.

Thanks.

**Comment by ikappas** [comment]
@eduardoklosowski Great to have this resolved. Please feel free to reopen if you still have issues
