### ISSUE TITLE
after the first 1-2 files it seems to be stopped

### ISSUE THREAD

**Issue by rrd108** [ikappas/vscode-phpcs#62]
If I start vscode and open a PHP file (foo.php) the linter shows the problems. I open an other file (bar.php) and no problems showed.

On the output I can see linting started on: file: foo.php and linting completed on: file: foo.php, and there is nothing for bar.php

The 2 files are similar, about 100 lines of code.

My system
Ubuntu 17.04
VScode 1.16.1

**Comment by ikappas** [comment]
@rrd108 Thank you for submitting an issue. 

I encountered a similar issue on Windows where the stdin spawn pipe was closed and an unhandled exception was thrown crashing the phpcs-server. Can you please install the latest `develop` branch and test whether your issue is resolved as this has been fixed there.

**Comment by ikappas** [comment]
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.

On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.
