### ISSUE TITLE
How to use ruleset.xml if it exists in the project?

### ISSUE THREAD

**Issue by chimit** [ikappas/vscode-phpcs#64]
I want to use a standard `ruleset.xml` if it exists in the project folder. Otherwise, use PSR2. Is it possible to get this behavior?

**Comment by ikappas** [comment]
@chimit 

You can configure the `phpcs.standard` to either the path to your projects ruleset.xml **or** the name of an available standard such as PSR2. 

If you leave `phpcs.standard=null` It will use the globally defined default standard which is PSR2 but it is not recommended.

As best practice it is better to configure your project's coding standard even for PSR2. This will keep your project configured correctly even if you decide to change the default global standard to something else for whatever reason. It also promotes better collaboration with others if you have these settings distributed via git.

**Comment by chimit** [comment]
Yes, I have a project's coding standard in `ruleset.xml`, but it's ignored by the VS Code PHPCS.

**Comment by ikappas** [comment]
@chimit if the standard resides at the root of your workspace you can set : 
```json
"phpcs.standard": "ruleset.xml"
```

**Comment by chimit** [comment]
Yes, but it's a little bit strange for me after my Atom experience. Maybe it's better to make it like in Atom? Use `ruleset.xml` if it exists in the project, otherwise use plugin settings (set PSR2 as default). In this case, we don't need to change global PHPCS settings and plugin settings on every project.

**Comment by ikappas** [comment]
@chimit It is a matter of configuration. The `phpcs.standard` setting is consistent with the `phpcs --standard` option on the command line. Please see the [README.md](https://github.com/ikappas/vscode-phpcs/tree/develop/phpcs#phpcsstandard)

**Comment by chimit** [comment]
@ikappas I try to set
```
"phpcs.standard": "ruleset.xml"
```
as you recommended, but I get an error:
```
phpcs: The "ruleset.xml" coding standard set in your configuration is not installed. Please review your configuration an try again.
```

**Comment by chimit** [comment]
Another question. The setting `phpcs.standard` is global for the whole VS Code. So if my project has a `ruleset.xml` file it will be used, but what if another project doesn't have this file? Or has a `phpcs.xml` file?
