### ISSUE TITLE
Incorrect type. Expected "string" in settings.json file

### ISSUE THREAD

**Issue by glen-84** [ikappas/vscode-phpcs#7]
It's pointing to this:

```json
"phpcs.standard": null,
```

**Comment by ikappas** [comment]
Thank you for your feedback. 
Where do you get this error?

**Comment by glen-84** [comment]
When opening User Settings:

![vscode-phpcs-err](https://cloud.githubusercontent.com/assets/261509/14862707/ec70f52e-0cb2-11e6-90aa-e467cb5b7668.png)

**Comment by ikappas** [comment]
This is not an issue...and null is a valid value -- it is just not typed correctly in packages.json.

**Comment by ikappas** [comment]
Fixed in phpcs 0.6.1.
