### ISSUE TITLE
ETA for 1.0 stable?

### ISSUE THREAD

**Issue by ADmad** [ikappas/vscode-phpcs#72]
Hi, any timeline on stable release of 1.0? :slightly_smiling_face:

**Comment by ADmad** [comment]
Praying we'll perhaps get it as a Christmas present :smile:

**Comment by ADmad** [comment]
Sadly it seems @ikappas doesn't have enough time to maintain this plugin 😞 

Until 1.0.0 stable in released anyone landing here can check out the [phpcbf](https://marketplace.visualstudio.com/items?itemName=persoderlind.vscode-phpcbf) extension which allows you to auto format/fix possible errors using your phpcs rules.

**Comment by sirbrillig** [comment]
Maybe we can create a fork and publish a release there?

**Comment by ADmad** [comment]
@sirbrillig Someone with the time and expertise surely can. I personally am not proficient enough in typescript.

**Comment by ikappas** [comment]
@sirbrillig Instead of creating a new fork and publishing it I would prefer to add additional maintainers to this project!

@ADmad  I am currently swamped with other projects and I can't finish off 1.0.0 at the moment.

I 've almost finished multi-root workspace support which I have not yet committed to the repository. I am more than happy to push this code in and get people involved to finish off the implementation and launch v.1.0.0

The blocker was that the underlying "vscode-languageserver" package did not provide all the necessary parts to properly support multi-root workspaces when I was writing the code. Hopefully this is fixed by now.

**Comment by ADmad** [comment]
@ikappas No worries. I understand how difficult it can be to spare time for opensource work. 

As you know that major issue currently is not being able to specify the executable path for phpcs. You have already taken care of that by adding `phpcs.executablePath` on the `develop` branch. It would be great help if you could make a stable release with that feature.

You can then put out an announcement inviting maintainers to help you develop/maintain the extension.

Just my 2 cents.

**Comment by ikappas** [comment]
@ADmad Fair point... https://github.com/ikappas/vscode-phpcs/blob/develop/README.md

**Comment by ikappas** [comment]
To anyone interested I just pushed a feature branch for [Multi Root support](https://github.com/ikappas/vscode-phpcs/tree/feature/multi-root-configuration)

**Comment by ikappas** [comment]
I just pushed multi-root support in develop branch that needs testing

**Comment by ikappas** [comment]
I've just pushed 1.0.0-beta.6 on the development branch adding automatic configuration search. This is the last feature for the 1.0.0 release which needs some testing before 1.0.0 launch.

**Comment by ikappas** [comment]
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.

On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.

**Comment by ADmad** [comment]
Awesome, thank you very much @ikappas.
