### ISSUE TITLE
Linting never completes

### ISSUE THREAD

**Issue by AashikP** [ikappas/vscode-phpcs#74]
First, thank you for the wonderful plugin. 

Regarding the issue, 
I have [this (vscode-phpcs/issues/1) ](https://github.com/ikappas/vscode-phpcs/issues/1) same issue with latest version of vscode and extension, running with phpcs 3.2.0.

![phpcs](https://user-images.githubusercontent.com/17475174/33998884-e8ff868a-e10e-11e7-8148-6e7e8455a8d4.png)

Output only displays:
`linting started on: file:///f%3A/xampp/htdocs/path/to/file/filename.php
`

I do not believe its an issue with phpcs  since linting works fine on sublime and atom even with the latest version of phpcs installed. 

**Current fix:** 
**Downgrading phpcs to an older version (3.0.1) has fixed the issue for me.**

**Comment by sirbrillig** [comment]
I don't have any ideas, but I thought it might help to mention that I'm running phpcs 3.2 and the latest vscode without any linting issues. It's possible that there's something going on with the output of phpcs though, as seen in [this issue](https://href.li/?https://youtrack.jetbrains.com/issue/WI-39190).

**Comment by pamtbaau** [comment]
1. Upgrading to PHP_Codesniffer 3.2.0: phpcs never completes.
2. Reverting to PHP_Codesniffer 3.0.1: phpcs works fine.
3. Upgrading to PHP_Codesniffer 3.2.0: phpcs never completes.

Environment:
Windows 10
Vscode: 1.19.0

**Comment by AashikP** [comment]
This issue is resolved in the latest version, **PHPCS 3.2.2**

**Comment by pamtbaau** [comment]
@AashikP It's working fine again. Thanks!
