### ISSUE TITLE
question: is it possible to Ignore specific rule?

### ISSUE THREAD

**Issue by str** [ikappas/vscode-phpcs#75]
I want to ignore the "Line exceeds 120". Is it possible to ignore just that rule without creating a full new ruleset?

**Comment by sirbrillig** [comment]
In phpcs 3.2, you can do this by adding something like this at the end of the line, although you'll need to replace `SNIFF.CODE` with whatever sniff code you want to disable: `// phpcs:disable SNIFF.CODE`. See [the official wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file) for more details.

I'm not sure how to get the sniff code with this plugin... typically it would show with the error message. You can always try running it manually like `phpcs -s myFile.php` to find the code.

**Comment by sirbrillig** [comment]
(It looks like [it will be possible to show the sniff code](https://github.com/ikappas/vscode-phpcs/issues/55) in 1.0.0)

**Comment by ikappas** [comment]
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.

On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.

**Comment by cagross** [comment]
@ikappas So currently, is it possible to ignore one particular rule in `vscode-phpcs`?  If so, can you point me to documentation on how to do that?
