### ISSUE TITLE
"The PHP CodeSniffer Linter server crashed 5 times in the last 3 minutes. The server will not be restarted."

### ISSUE THREAD

**Issue by CharlesWiltgen** [ikappas/vscode-phpcs#76]
Hi! I just discovered `vscode-phpcs`, which I'm thrilled exists.

I get the "Linter server crashed" above when using the plug-in, even though using phpcs from the command line on the same file works fine.

Is there additional information I can provide that would help you narrow down the issue?

**Comment by CharlesWiltgen** [comment]
Additional info: I've reproduced this with CodeSniffer 3.2.0 and 3.2.1.

**Comment by jamesh38** [comment]
Any luck on this @CharlesWiltgen? Running into the same issue.

**Comment by ikappas** [comment]
@CharlesWiltgen @jamesh38 Which version of the plugin are you using? Have you tried the latest beta on development branch?

**Comment by ikappas** [comment]
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.

On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.
