### ISSUE TITLE
Relint the file when it's externally modified

### ISSUE THREAD

**Issue by Darkein** [ikappas/vscode-phpcs#82]
Hello,

I'm using vscode-phpcs with phpcbf. Unfortunately when phpcbf format the file, I always see the errors in the file until i modify and save it.
Can you parse the file whenever it changes?

Thanks!

**Comment by ikappas** [comment]
@Darkein I could not reproduce the error with vscode-phpcs.1.0.0

**Comment by Darkein** [comment]
vscode-phpcbf is broken since it's last release.
But if i launch phpcbf in command-line, i have some remaining errors. I will send you a animated gif for a better explanation

**Comment by Darkein** [comment]
Here we are. The comportment is the same with vscode-phpcbf:
(at the end of the gif, i just add and remove a space, and save the file)

![phpcs error](https://user-images.githubusercontent.com/4948463/36484106-79157a10-1718-11e8-813d-e4d9a6d1efc4.gif)

**Comment by ikappas** [comment]
@Darkein If you notice there are 22 remaining issues after the fix. Right about the end of the gif loop you can see the problems count go to 22... It just takes around 2 secs for the file system update to register and re-lint the document. (I've read somewhere that this delay is a vscode hack)

**Comment by Darkein** [comment]
I've just reloaded my vscode and my vscode-phpcs has been updated. I don't have the problem anymore with the 1.0.1 version.

Thanks!

**Comment by ikappas** [comment]
@Darkein Nice to hear you got it resolved!
