### ISSUE TITLE
List the name of the sniff in addition to the problem

### ISSUE THREAD

**Issue by Everspace** [ikappas/vscode-phpcs#87]
This would allow it to be easier to remove particular sniffs from particular files.

For example I am writing some things to interact with Wordpress, and so I wish to run the Wordpress coding standards. However I'm doing so via the command-line and shell, so the "OutputNotEscaped" sniff is not very helpful to me. Having to go digging for it is even more obnoxious.

Preferably like other linters (and like you would get via commandline) it should display the rule that is causing the problem.

For example:
```
All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'MY_DEFINITION'. (WordPress.XSS.EscapeOutput.OutputNotEscaped)
```

**Comment by ikappas** [comment]
@Everspace This has been implemented in phpcs@1.0.0-beta.x which is available in the development branch.
