### ISSUE TITLE
Different phpcs.standard settings for different folders in same workspace are not taken into consideration

### ISSUE THREAD

**Issue by mwidmann** [ikappas/vscode-phpcs#88]
I have a workspace where I have four folders in. Three of the folders are WordPress related and therefore should be treated with the WordPress-Extra standards definition. The last one is a framework agnostic module that should be treated with the PSR2 standards.

Now it looks as if the standard used is the one in the `.vscode/settings.json` of the first file that's loaded and not the one for the folder (order the overall workspace settings one) if it's not present.

PHP_CodeSniffer is installed in version 2.9.1
PHP is 7.1.14
VS Code is 1.20.1
phpcs Plugin Version is 0.7.0

**Comment by anteprimorac** [comment]
How I can see this plugin doesn't have support for workspaces.

**Comment by mwidmann** [comment]
I wouldn't say that. As you can set the a different Standard than the default in your workspace settings.

**Comment by anteprimorac** [comment]
Yes, but it can only read workspace and first folder settings. It should work same as cli command. You can have phpcs config only for particular part of your application. But this plugin will only use config file from root of your application or path defined in vscode settings.

**Comment by ikappas** [comment]
I just pushed multi-root support in develop branch that needs testing

**Comment by ikappas** [comment]
Also join the discussion on #73

**Comment by ikappas** [comment]
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.

On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.
