### ISSUE TITLE
Does not shows errors onType

### ISSUE THREAD

**Issue by codewp** [ikappas/vscode-phpcs#9]
This extension does not shows errors onType although `"php.validate.run": "onType"` is exists in user settings.

This extension shows errors after saving file.

`Visual Studio Code information.  
Version 1.0.0  
Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8  
Date 2016-04-13T14:21:33.326Z  
Shell 0.35.6  
Renderer 45.0.2454.85  
Node 4.1.1  
On Ubuntu 14.4  
`

**Comment by ikappas** [comment]
Hi @codewp and thank you for your feedback.

This is by design. phpcs cannot work with in-memory files and performs linting only on existing filesystem files. That is why it only works on save.
