### ISSUE TITLE
setting for "phpcs.extensions" was removed in 1.0.0. Is there a replacement?

### ISSUE THREAD

**Issue by briantully** [ikappas/vscode-phpcs#92]
First off, thank you for the new 1.0.0 version which allows me to specify my global composer installed phpcs :)

I noticed that in the 1.0.0 version that there are some changes in configuration namespacing, specifically for the following:

- "phpcs.ignore" was changed to "phpcs.ignorePatterns" and is now an array
- "phpcs.extensions" reports "Unknown configuration" in settings.json, so appears to have been removed. Is there a replacement for this setting that allows one to specify which file extensions phpcs should parse?

Thanks again!

**Comment by ikappas** [comment]
@briantully You are welcome! There was never an `phpcs.extensions` configuration setting ;)

The plugin works on any file association that is registered for PHP. So for example associating *.inc files with php is easily done like so:
```json
"files.associations": {
  "*.inc": "php"
} 
```
See also:
https://stackoverflow.com/questions/42802259/does-vscode-editor-support-inc-file-highlight
https://code.visualstudio.com/updates/vMarch#_editor

**Comment by briantully** [comment]
Thanks! I don't know where phpcs.extensions came from, perhaps from trying another phpcs plugin for vscode.

Thanks again for all your hard work!

**Comment by bwaindwain** [comment]
This extension "works" for php filetypes. But PHP Codesniffer will only scan  .inc, .php, .js or .css files.

See https://github.com/ikappas/vscode-phpcs/issues/159
