### ISSUE TITLE
phpcs.executablePath not work on Windows 10

### ISSUE THREAD

**Issue by rivetweb** [ikappas/vscode-phpcs#97]
i tryed

`"phpcs.executablePath": "C:/Users/user/bin/PHP_CodeSniffer/vendor/bin/phpcs.bat"`

and this

`"phpcs.executablePath": "C:\\Users\\user\\bin\\PHP_CodeSniffer\\vendor\\bin\\phpcs.bat"`

- from command line - it work
- from vscode 1.20.1 - not work

**Comment by rivetweb** [comment]
here full content of site1.code-workspace

```
{
	"folders": [
		{
			"path": "../../web/site1/"
		}
	],
	"settings": {
		"files.autoGuessEncoding": true,
		"php-cs-fixer.executablePath": "~/bin/PHP-CS-Fixer/php-cs-fixer",
		"php-cs-fixer.executablePathWindows": "~/bin/PHP-CS-Fixer/php-cs-fixer.bat",
		"phpcs.enable": true,
		"phpcs.executablePath": "C:\\Users\\user\\bin\\PHP_CodeSniffer\\vendor\\bin\\phpcs.bat"
	}
}
```

**Comment by ikappas** [comment]
@rivetweb What error are you getting in vscode?

**Comment by rivetweb** [comment]
i dont have any errors
checking just not work

**Comment by ikappas** [comment]
@rivetweb Have a look at "phpcs.trace.server": "messages" which will show additional information in  VSCode  > Output pane > PHP Code Sniffer section.

Also note that Windows linting is quite slower than in linux/mac so it takes more time for the errors to come up.

**Comment by rivetweb** [comment]
i have a project with 1-3 php files

didnt have any output for this extension
its enabled and installed

also now installing php sniffer from composer 
not work in Windows 10

**Comment by ikappas** [comment]
@rivetweb After adding "phpcs.trace.server": "messages" in your vscode user settings then you need to open a php file to load the extension. Once loaded you should see output in VSCode > Output pane > PHP Code Sniffer

**Comment by ikappas** [comment]
@rivetweb Can you provide a reproduction repository?

**Comment by rivetweb** [comment]
all works
i have problem if php not installed globally
i fix this script https://github.com/rivetweb/PHP_CodeSniffer/blob/bitrix/phpcs.bat and replace vendor/bin/phpcs.bat

**Comment by flyke** [comment]
For me it was not working with phpcs installed globally via composer.
Although not mentionned, the problem lied in the source of my php executable. I use Ampps (like Xamp/Mamp) for localhosting my php sites and I had to change %userprofile%\AppData\Roaming\Composer\vendor\bin\phpcs.bat to the correct php path.
Changed it from:

@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../squizlabs/php_codesniffer/bin/phpcs
php "%BIN_TARGET%" %*

To:

@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../squizlabs/php_codesniffer/bin/phpcs
"C:\Program Files (x86)\Ampps\php-7.1\php" "%BIN_TARGET%" %*

For reference: in VSCode, in the PHP CodeSniffer settings, this is what I have for my Executable Path:
C:/Users/MYUSERNAME/AppData/Roaming/Composer/vendor/bin/phpcs.bat
